### ISSUE TITLE
Creating multiple instances of one environment with different configurations

### ISSUE THREAD

**Issue by shlomihod** [zykls/whynot#19]
I'd like to create a multiple instances of one environment (e.g., Credit) with different configurations (e.g., each one of them with only subset of the data).

How can I do that? It seems that `gym.make` doesn't support that, so even creating my own modified version of a simulator won't work (except of creating multiple sub-packages, as many as different configuration I want)

**Comment by millerjohnp** [comment]
Great question. This isn't currently possible, but it should be fairly straightforward to add this functionality. I'll take a look today and get something working.

**Comment by millerjohnp** [comment]
I've added a PR that makes it possible to run `Credit` the environment with different datasets. For instance, to subsample the dataset, you'd use
```
import whynot as wn
import whynot.gym as gym

# Only use features and labels for the first 100 agents
all_features, all_labels = wn.credit.CreditData.features, wn.credit.CreditData.labels
features, labels = all_features[:100], all_labels[:100]
env = gym.make('Credit-v0', initial_state=wn.credit.State(features, labels))
```
Does this look like what you had in mind?

**Comment by shlomihod** [comment]
Thanks! It definitely helps.
Can I create multiple instances of the same environment?

**Comment by millerjohnp** [comment]
Yes, with this PR you can also create multiple instances of the same environment, e.g.
```python
import whynot as wn
import whynot.gym as gym

env_1 = gym.make('Credit-v0')
env_2 = gym.make('Credit-v0')

env_1 is env_2
# False
```
Does this addresses your issue? If so, I'll merge the PR and close this.

**Comment by shlomihod** [comment]
Great, thanks!
